/**
 * Writes supabase/seed.sql from the deterministic SQLite seed (data/claims.seed.db), so Supabase holds exactly the
 * same 80 MOCK claims the tests assert on. Run `npm run seed` first, then `npm run seed:sql`.
 * The SQL is idempotent: it replaces departments, employees, claims and the pristine copy used by reset_demo().
 */
import Database from "better-sqlite3";
import fs from "node:fs";
import { SEED_DB_PATH } from "../src/lib/db";

const db = new Database(SEED_DB_PATH, { readonly: true });
const q = (v: unknown) => (v === null || v === undefined ? "null" : typeof v === "number" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const rows = (t: string) => db.prepare(`select * from ${t} order by id`).all() as Record<string, unknown>[];
const insert = (table: string, cols: string[], data: Record<string, unknown>[]) =>
  `insert into ${table} (${cols.join(", ")}) ${table.startsWith("public.claims") ? "overriding system value " : ""}values\n` +
  data.map((r) => `  (${cols.map((c) => q(r[c])).join(", ")})`).join(",\n") + ";\n";

const claimCols = ["id", "employee_id", "category", "merchant", "amount", "transaction_date", "transaction_time", "description",
  "receipt_path", "receipt_hash", "manager_status", "submitted_at", "source", "audit_status", "audit_reason", "audit_note", "audited_at", "audited_by"];
const claims = rows("claims");

const sql = `-- GENERATED by scripts/seed-sql.ts. MOCK data only. Do not edit by hand.
begin;
delete from public.claims where true; delete from public.claims_seed where true;
delete from public.employees where true; delete from public.departments where true;
${insert("public.departments", ["id", "name"], rows("departments"))}
${insert("public.employees", ["id", "name", "department_id", "manager_name"], rows("employees"))}
${insert("public.claims", claimCols, claims)}
insert into public.claims_seed overriding system value select * from public.claims;
select setval(pg_get_serial_sequence('public.claims', 'id'), (select max(id) from public.claims));
commit;
`;
fs.mkdirSync("supabase", { recursive: true });
fs.writeFileSync("supabase/seed.sql", sql);
console.log(`supabase/seed.sql: ${claims.length} claims, ${rows("employees").length} employees, ${rows("departments").length} departments`);
