-- Claim Audit demo: claims data in Supabase Postgres (master-plan v2.6).
-- All data is MOCK. Writes go only through the functions below (security definer, role checked inside);
-- tables have no insert/update/delete policies, so the API cannot write to them directly.

create table if not exists public.departments (
  id integer primary key,
  name text not null
);

create table if not exists public.employees (
  id integer primary key,
  name text not null,
  department_id integer not null references public.departments(id),
  manager_name text not null
);

create table if not exists public.claims (
  id integer generated by default as identity primary key,
  employee_id integer not null references public.employees(id),
  category text not null,
  merchant text not null,
  amount bigint not null check (amount > 0),
  transaction_date text not null check (transaction_date ~ '^\d{4}-\d{2}-\d{2}$'),
  transaction_time text check (transaction_time is null or transaction_time ~ '^\d{2}:\d{2}$'),
  description text not null,
  receipt_path text,
  receipt_hash text,
  manager_status text not null default 'approved',
  submitted_at text not null,
  source text not null default 'seed' check (source in ('seed', 'demo')),
  audit_status text not null default 'pending' check (audit_status in ('pending', 'approved', 'rejected')),
  audit_reason text,
  audit_note text,
  audited_at text,
  audited_by text
);

-- Pristine copy used by reset_demo().
create table if not exists public.claims_seed (like public.claims including defaults);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null
);

-- ---- Who is calling (from the Supabase JWT; app_metadata cannot be edited by users) ----
create or replace function public.app_role() returns text
language sql stable as $$ select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') $$;

create or replace function public.app_employee_id() returns integer
language sql stable as $$ select nullif(auth.jwt() -> 'app_metadata' ->> 'employee_id', '')::integer $$;

-- ---- Read access (RLS) ----
alter table public.departments enable row level security;
alter table public.employees enable row level security;
alter table public.claims enable row level security;
alter table public.claims_seed enable row level security;
alter table public.settings enable row level security;

drop policy if exists "app users read departments" on public.departments;
create policy "app users read departments" on public.departments for select to authenticated
  using (public.app_role() in ('finance', 'employee'));

drop policy if exists "app users read employees" on public.employees;
create policy "app users read employees" on public.employees for select to authenticated
  using (public.app_role() in ('finance', 'employee'));

drop policy if exists "finance reads all claims, employees their own" on public.claims;
create policy "finance reads all claims, employees their own" on public.claims for select to authenticated
  using (public.app_role() = 'finance' or (public.app_role() = 'employee' and employee_id = public.app_employee_id()));

drop policy if exists "app users read settings" on public.settings;
create policy "app users read settings" on public.settings for select to authenticated
  using (public.app_role() in ('finance', 'employee'));
-- claims_seed: no policies = no API access.

create or replace view public.claims_v with (security_invoker = true) as
  select c.*, e.name as employee_name, e.manager_name, d.name as department_name
  from public.claims c
  join public.employees e on e.id = c.employee_id
  join public.departments d on d.id = e.department_id;

grant select on public.departments, public.employees, public.claims, public.settings, public.claims_v to authenticated;
revoke all on public.claims_seed from anon, authenticated;
revoke all on public.claims_v from anon;

-- Minimal fields of every claim for the duplicate check, so an employee's own claim is checked against everyone's
-- without exposing names, merchants' owners or other details.
create or replace function public.dup_keys()
returns table (id integer, amount bigint, transaction_date text, merchant text, receipt_hash text)
language sql stable security definer set search_path = public as $$
  select id, amount, transaction_date, merchant, receipt_hash from public.claims
  where public.app_role() in ('finance', 'employee')
$$;

-- ---- Writes ----
create or replace function public.decide_claim(p_id integer, p_status text, p_reason text, p_note text)
returns integer language plpgsql security definer set search_path = public as $$
declare n integer;
begin
  if public.app_role() <> 'finance' then raise exception 'not allowed' using errcode = '42501'; end if;
  if p_status not in ('approved', 'rejected') then raise exception 'bad status'; end if;
  update public.claims set audit_status = p_status, audit_reason = p_reason, audit_note = left(p_note, 300),
    audited_at = to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), audited_by = auth.jwt() ->> 'email'
  where id = p_id and audit_status = 'pending';
  get diagnostics n = row_count;
  return n; -- 0 = already decided (by another screen)
end $$;

create or replace function public.undo_decision(p_id integer)
returns void language plpgsql security definer set search_path = public as $$
begin
  if public.app_role() <> 'finance' then raise exception 'not allowed' using errcode = '42501'; end if;
  update public.claims set audit_status = 'pending', audit_reason = null, audit_note = null, audited_at = null, audited_by = null
  where id = p_id;
end $$;

create or replace function public.approve_many(p_ids integer[])
returns integer language plpgsql security definer set search_path = public as $$
declare n integer;
begin
  if public.app_role() <> 'finance' then raise exception 'not allowed' using errcode = '42501'; end if;
  update public.claims set audit_status = 'approved',
    audited_at = to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), audited_by = auth.jwt() ->> 'email'
  where id = any(p_ids) and audit_status = 'pending';
  get diagnostics n = row_count;
  return n;
end $$;

create or replace function public.submit_claim(p_category text, p_merchant text, p_amount bigint, p_date text, p_time text,
  p_description text, p_receipt_path text, p_receipt_hash text)
returns integer language plpgsql security definer set search_path = public as $$
declare new_id integer; emp integer := public.app_employee_id();
begin
  if public.app_role() <> 'employee' or emp is null then raise exception 'not allowed' using errcode = '42501'; end if;
  insert into public.claims (employee_id, category, merchant, amount, transaction_date, transaction_time, description,
    receipt_path, receipt_hash, manager_status, submitted_at, source)
  values (emp, p_category, p_merchant, p_amount, p_date, nullif(p_time, ''), p_description,
    p_receipt_path, p_receipt_hash, 'approved', to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), 'demo')
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.put_setting(p_key text, p_value jsonb)
returns void language plpgsql security definer set search_path = public as $$
begin
  if public.app_role() <> 'finance' then raise exception 'not allowed' using errcode = '42501'; end if;
  insert into public.settings (key, value) values (p_key, p_value) on conflict (key) do update set value = excluded.value;
end $$;

create or replace function public.delete_setting(p_key text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if public.app_role() <> 'finance' then raise exception 'not allowed' using errcode = '42501'; end if;
  delete from public.settings where key = p_key;
end $$;

-- Restores the 80 seed claims and clears decisions, demo submissions and rule changes.
create or replace function public.reset_demo()
returns void language plpgsql security definer set search_path = public as $$
begin
  if public.app_role() <> 'finance' then raise exception 'not allowed' using errcode = '42501'; end if;
  delete from public.claims where true;
  insert into public.claims overriding system value select * from public.claims_seed;
  perform setval(pg_get_serial_sequence('public.claims', 'id'), (select coalesce(max(id), 0) from public.claims));
  delete from public.settings where true;
end $$;

revoke execute on function public.decide_claim, public.undo_decision, public.approve_many, public.submit_claim,
  public.put_setting, public.delete_setting, public.reset_demo, public.dup_keys from public, anon;
grant execute on function public.decide_claim, public.undo_decision, public.approve_many, public.submit_claim,
  public.put_setting, public.delete_setting, public.reset_demo, public.dup_keys, public.app_role, public.app_employee_id to authenticated;

-- ---- Receipt photos: private bucket; employees upload, app users read ----
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('receipts', 'receipts', false, 8388608, array['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
on conflict (id) do nothing;

drop policy if exists "employees upload receipts" on storage.objects;
create policy "employees upload receipts" on storage.objects for insert to authenticated
  with check (bucket_id = 'receipts' and public.app_role() = 'employee');

drop policy if exists "app users read receipts" on storage.objects;
create policy "app users read receipts" on storage.objects for select to authenticated
  using (bucket_id = 'receipts' and public.app_role() in ('finance', 'employee'));

drop policy if exists "finance deletes receipts" on storage.objects;
create policy "finance deletes receipts" on storage.objects for delete to authenticated
  using (bucket_id = 'receipts' and public.app_role() = 'finance');
